### ISSUE TITLE
ログイン画面

### ISSUE THREAD

**Issue by clucker357** [dec-teamb-phase2/Forget_Shopping_list#2]
ユーザが自身の買い物リストにアクセスする際に、IDとパスワードを入力する画面。

**Comment by ReiA-O** [comment]
user:test_user1
mail:example@email.com
pass:123456789

**Comment by ReiA-O** [comment]
使用したコマンド
./vendor/bin/sail composer require laravel/breeze --dev
./vendor/bin/sail php artisan breeze:install
./vendor/bin/sail npm install
./vendor/bin/sail npm run build
./vendor/bin/sail php artisan migrate


変更点
// database/seeders/DatabaseSeeder.php

<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class DatabaseSeeder extends Seeder
{
  /**
   * Seed the application's database.
   *
   * @return void
   */
  public function run()
  {
    // 🔽 この行のコメントから外す
    \App\Models\User::factory(10)->create();

    // 🔽 こちらはそのまま
    // \App\Models\User::factory()->create([
    //     'name' => 'Test User',
    //     'email' => 'test@example.com',
    // ]);

  }
}


その後のコマンド
./vendor/bin/sail php artisan db:seed

**Comment by clucker357** [comment]
使用したコマンド
php artisan key:generate
php artisan migrate
composer require laravel/breeze --dev
php artisan breeze:install
npm install
npm run build
php artisan migrate
php artisan db:seed
