### ISSUE TITLE
削除の方式をデータベースからの完全な削除ではなく、削除済みという要素をアイテムに付け足す形式にする。

### ISSUE THREAD

**Issue by clucker357** [dec-teamb-phase2/Forget_Shopping_list#33]
アイテムデータの要素に削除されているかいないかを管理する変数(flagのようなもの)を用意して、その変数を動かすことによって、アイテムの状態を管理する。

**Comment by ReiA-O** [comment]
方式1：データベース間の移動(ITEM_LIST→削除済みリスト)
方式2：フラグをたててそれに準じた扱いをする
