### ISSUE TITLE
CREATEしたアイテムは上位hoge個を除いてhoge日でリスト(作成順ソート)から消去される

### ISSUE THREAD

**Issue by ReiA-O** [dec-teamb-phase2/Forget_Shopping_list#42]
削除する機能はできているが条件付き削除ができていないので

**Comment by clucker357** [comment]
仮の機能として、上位3個のアイテムを除いて、2分でitemテーブルから削除される機能を作成します。

**Comment by clucker357** [comment]
ddなどを用いて調べた結果、prune(現在の自動削除を担っている箇所)は人間の目で見て理解できる形式の出力では無さそうだったので、削除の部分のプログラムを変更する手順では実現が難しいと思います。
代わりに、削除したアイテムの内、最近削除されたアイテムを表示するような仕組みを実現する方向での検討をしようと考えています。
